#! /bin/sh
### BEGIN INIT INFO
# Provides:		river
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	river - Comet server
# Description:		river - Comet server
### END INIT INFO
 
 
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/river
DAEMON_ARGS=/etc/river.conf
NAME=river
DESC=river
PIDFILE=/var/run/river.pid
 
test -x $DAEMON || exit 0
 
case "$1" in
  start)
	echo -n "Starting $DESC: "
	touch $PIDFILE
	if start-stop-daemon --background --start --quiet --make-pidfile --umask 007 --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	;;
 
  restart|force-reload)
	${0} stop
	${0} start
	;;
  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac
 
exit 0
